/**
 * Identifier generation for `effect-auth`.
 *
 * Every row this library writes is keyed by a UUIDv7 string generated by the
 * application rather than by the database. Version 7 encodes a millisecond
 * timestamp in its leading 48 bits, so ids sort chronologically: a B-tree index
 * on the primary key stays append-only instead of fragmenting the way random
 * UUIDv4 keys do, and `ORDER BY id` is a usable tiebreaker for rows written in
 * the same millisecond.
 *
 * **Details**
 *
 * The timestamp comes from the Effect `Clock`, never from `Date.now()`, so ids
 * minted under `TestClock` carry the test's virtual time and remain ordered
 * with respect to everything else the test does.
 *
 * **Gotchas**
 *
 * The model classes in `domain/Schema.ts` already generate their own ids
 * through `Model.UuidV7Insert`, so `User.insert.make({ ... })` needs nothing
 * from this module. Reach for it only when an id must exist *before* the row
 * does — correlating a log line with a write, or seeding fixtures.
 *
 * @since 1.0.0
 */
import { Effect } from "effect"
import type { AccountId, SessionId, UserId } from "./Schema.js"

/**
 * The largest timestamp a UUIDv7 can carry: 48 bits of milliseconds, which runs
 * out in the year 10889.
 *
 * @category constructors
 * @since 1.0.0
 */
export const maxTimestampMillis = 2 ** 48 - 1

const byteToHex: ReadonlyArray<string> = Array.from(
  { length: 256 },
  (_, byte) => byte.toString(16).padStart(2, "0")
)

const format = (bytes: Uint8Array): string => {
  let out = ""
  for (let i = 0; i < 16; i++) {
    out += byteToHex[bytes[i]!]
    if (i === 3 || i === 5 || i === 7 || i === 9) out += "-"
  }
  return out
}

/**
 * Writes a UUIDv7 into `bytes`, which must hold 16 cryptographically random
 * bytes, and returns its canonical string form.
 *
 * **Details**
 *
 * The first six bytes become the big-endian millisecond timestamp, the high
 * nibble of byte 6 becomes the version (`0b0111`) and the top two bits of byte
 * 8 become the RFC 9562 variant. Every other bit is left random.
 *
 * **Gotchas**
 *
 * `bytes` is mutated in place. Timestamps outside `0 .. maxTimestampMillis` are
 * clamped rather than rejected, so a clock that has gone backwards still yields
 * a well-formed id.
 *
 * @category constructors
 * @since 1.0.0
 */
export const makeUnsafe = (timestampMillis: number, bytes: Uint8Array): string => {
  const timestamp = Math.min(Math.max(0, Math.trunc(timestampMillis)), maxTimestampMillis)
  bytes[0] = Math.floor(timestamp / 2 ** 40) & 0xff
  bytes[1] = Math.floor(timestamp / 2 ** 32) & 0xff
  bytes[2] = Math.floor(timestamp / 2 ** 24) & 0xff
  bytes[3] = Math.floor(timestamp / 2 ** 16) & 0xff
  bytes[4] = Math.floor(timestamp / 2 ** 8) & 0xff
  bytes[5] = timestamp & 0xff
  bytes[6] = (bytes[6]! & 0x0f) | 0x70
  bytes[8] = (bytes[8]! & 0x3f) | 0x80
  return format(bytes)
}

/**
 * A fresh UUIDv7, timestamped from the Effect `Clock` and filled from the
 * runtime's cryptographic random source.
 *
 * @category constructors
 * @since 1.0.0
 */
export const uuidV7: Effect.Effect<string> = Effect.clockWith((clock) =>
  Effect.sync(() =>
    makeUnsafe(clock.currentTimeMillisUnsafe(), globalThis.crypto.getRandomValues(new Uint8Array(16)))
  )
)

/**
 * Reads the millisecond timestamp back out of a UUIDv7 string.
 *
 * **When to use**
 *
 * Use in tests and diagnostics to assert that ids were minted in the order the
 * flow claims, without depending on a separate timestamp column.
 *
 * @category combinators
 * @since 1.0.0
 */
export const timestampOf = (uuid: string): number => Number.parseInt(uuid.slice(0, 8) + uuid.slice(9, 13), 16)

const uuidV7Pattern = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/

/**
 * Whether a string is a canonical lowercase UUID with version 7 and the RFC
 * 9562 variant.
 *
 * @category guards
 * @since 1.0.0
 */
export const isUuidV7 = (value: string): boolean => uuidV7Pattern.test(value)

/**
 * A fresh {@link UserId}.
 *
 * @category constructors
 * @since 1.0.0
 */
export const userId: Effect.Effect<UserId> = Effect.map(uuidV7, (id) => id as UserId)

/**
 * A fresh {@link SessionId}.
 *
 * @category constructors
 * @since 1.0.0
 */
export const sessionId: Effect.Effect<SessionId> = Effect.map(uuidV7, (id) => id as SessionId)

/**
 * A fresh {@link AccountId}.
 *
 * @category constructors
 * @since 1.0.0
 */
export const accountId: Effect.Effect<AccountId> = Effect.map(uuidV7, (id) => id as AccountId)
