/**
 * Identifier generation for `effect-auth`.
 *
 * Every row this library writes is keyed by a UUIDv7 string generated by the
 * application rather than by the database. Version 7 encodes a millisecond
 * timestamp in its leading 48 bits, so ids sort chronologically: a B-tree index
 * on the primary key stays append-only instead of fragmenting the way random
 * UUIDv4 keys do, and `ORDER BY id` is a usable tiebreaker for rows written in
 * the same millisecond.
 *
 * **Details**
 *
 * The timestamp comes from the Effect `Clock`, never from `Date.now()`, so ids
 * minted under `TestClock` carry the test's virtual time and remain ordered
 * with respect to everything else the test does.
 *
 * **Gotchas**
 *
 * The model classes in `domain/Schema.ts` already generate their own ids
 * through `Model.UuidV7Insert`, so `User.insert.make({ ... })` needs nothing
 * from this module. Reach for it only when an id must exist *before* the row
 * does — correlating a log line with a write, or seeding fixtures.
 *
 * @since 0.1.0
 */
import { Crypto, Effect } from "effect"
import { AccountId, SessionId, UserId } from "./Schema.js"

/**
 * A fresh UUIDv7, timestamped from the Effect `Clock` and filled from the
 * ambient `Crypto` service's random source.
 *
 * **Details**
 *
 * This is `Crypto.randomUUIDv7` — RFC 9562 layout, timestamp clamped into the
 * 48 bits it has, every other bit random — with its `PlatformError` turned
 * into a defect: a runtime that cannot produce random bytes is broken, not
 * badly asked.
 *
 * @category constructors
 * @since 0.1.0
 */
export const uuidV7: Effect.Effect<string, never, Crypto.Crypto> = Effect.orDie(
  Crypto.Crypto.use((crypto) => crypto.randomUUIDv7)
)

/**
 * Reads the millisecond timestamp back out of a UUIDv7 string.
 *
 * **When to use**
 *
 * Use in tests and diagnostics to assert that ids were minted in the order the
 * flow claims, without depending on a separate timestamp column.
 *
 * @category combinators
 * @since 0.1.0
 */
export const timestampOf = (uuid: string): number => Number.parseInt(uuid.slice(0, 8) + uuid.slice(9, 13), 16)

const uuidV7Pattern = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/

/**
 * Whether a string is a canonical lowercase UUID with version 7 and the RFC
 * 9562 variant.
 *
 * @category guards
 * @since 0.1.0
 */
export const isUuidV7 = (value: string): boolean => uuidV7Pattern.test(value)

/**
 * A fresh {@link UserId}.
 *
 * @category constructors
 * @since 0.1.0
 */
export const userId: Effect.Effect<UserId, never, Crypto.Crypto> = Effect.map(uuidV7, (id) => UserId.make(id))

/**
 * A fresh {@link SessionId}.
 *
 * @category constructors
 * @since 0.1.0
 */
export const sessionId: Effect.Effect<SessionId, never, Crypto.Crypto> = Effect.map(uuidV7, (id) => SessionId.make(id))

/**
 * A fresh {@link AccountId}.
 *
 * @category constructors
 * @since 0.1.0
 */
export const accountId: Effect.Effect<AccountId, never, Crypto.Crypto> = Effect.map(uuidV7, (id) => AccountId.make(id))
