/**
 * The persisted domain models of `effect-auth`.
 *
 * Every model is declared once with `Model.Class` from `effect/unstable/schema`,
 * which derives the database variants (`select` / `insert` / `update`) and the
 * JSON API variants (`json` / `jsonCreate` / `jsonUpdate`) from a single field
 * declaration. Fields that must never reach a client — session token hashes,
 * OAuth tokens, password hashes — are declared with `Model.Sensitive`, so the
 * JSON variants simply do not contain them.
 *
 * Identifiers are UUIDv7 strings generated by the application on insert
 * (sortable, index friendly). Timestamps are encoded as ISO-8601 strings: the
 * SQL layer therefore stores every timestamp column as `text`, which behaves
 * identically on PostgreSQL and SQLite and preserves lexicographic ordering.
 *
 * @since 1.0.0
 */
import { Schema } from "effect"
import { Model } from "effect/unstable/schema"

// -----------------------------------------------------------------------------
// Identifiers
// -----------------------------------------------------------------------------

/**
 * Branded identifier of a {@link User}. A UUIDv7 string.
 *
 * @category models
 * @since 1.0.0
 */
export const UserId = Schema.String.pipe(Schema.brand("UserId"))

/**
 * The type of a {@link UserId}.
 *
 * @category models
 * @since 1.0.0
 */
export type UserId = typeof UserId.Type

/**
 * Branded identifier of a {@link Session}. A UUIDv7 string.
 *
 * @category models
 * @since 1.0.0
 */
export const SessionId = Schema.String.pipe(Schema.brand("SessionId"))

/**
 * The type of a {@link SessionId}.
 *
 * @category models
 * @since 1.0.0
 */
export type SessionId = typeof SessionId.Type

/**
 * Branded identifier of an {@link Account}. A UUIDv7 string.
 *
 * @category models
 * @since 1.0.0
 */
export const AccountId = Schema.String.pipe(Schema.brand("AccountId"))

/**
 * The type of an {@link AccountId}.
 *
 * @category models
 * @since 1.0.0
 */
export type AccountId = typeof AccountId.Type

/**
 * Branded identifier of a {@link Verification}. A UUIDv7 string.
 *
 * @category models
 * @since 1.0.0
 */
export const VerificationId = Schema.String.pipe(Schema.brand("VerificationId"))

/**
 * The type of a {@link VerificationId}.
 *
 * @category models
 * @since 1.0.0
 */
export type VerificationId = typeof VerificationId.Type

/**
 * The schema used for e-mail addresses.
 *
 * **Details**
 *
 * Addresses are stored normalized (trimmed and lowercased) so that the unique
 * index on `users.email` is also a case-insensitive uniqueness guarantee. Use
 * {@link normalizeEmail} on every write and on every lookup key.
 *
 * @category models
 * @since 1.0.0
 */
export const Email = Schema.String

/**
 * Normalizes an e-mail address for storage and lookup: surrounding whitespace
 * is removed and the address is lowercased.
 *
 * **Gotchas**
 *
 * This must be applied to both sides of every comparison — writing a row and
 * looking one up — otherwise the unique index will not catch duplicates that
 * differ only in case.
 *
 * @category combinators
 * @since 1.0.0
 */
export const normalizeEmail = (email: string): string => email.trim().toLowerCase()

// -----------------------------------------------------------------------------
// User
// -----------------------------------------------------------------------------

/**
 * A registered end user.
 *
 * **Details**
 *
 * `email` is unique and always stored normalized (see {@link normalizeEmail}).
 * `emailVerified` is derived by the library — from a consumed verification
 * token or from a trusted OAuth provider claim — and is therefore excluded from
 * the JSON create/update variants so a client can never set it.
 *
 * @category models
 * @since 1.0.0
 */
export class User extends Model.Class<User>("effect-auth/User")({
  id: Model.UuidV7Insert(UserId),
  name: Schema.String,
  email: Email,
  emailVerified: Model.GeneratedByApp(Schema.Boolean),
  image: Schema.NullOr(Schema.String),
  createdAt: Model.DateTimeInsert,
  updatedAt: Model.DateTimeUpdate
}) {}

// -----------------------------------------------------------------------------
// Session
// -----------------------------------------------------------------------------

/**
 * An authenticated session.
 *
 * **Details**
 *
 * The raw session token is never persisted: only `tokenHash`, the base64url
 * SHA-256 digest of the opaque token, is stored, and it is declared
 * `Model.Sensitive` so it is absent from every JSON variant. A lookup hashes
 * the presented token and matches on the digest.
 *
 * @category models
 * @since 1.0.0
 */
export class Session extends Model.Class<Session>("effect-auth/Session")({
  id: Model.UuidV7Insert(SessionId),
  tokenHash: Model.Sensitive(Schema.String),
  userId: UserId,
  expiresAt: Schema.DateTimeUtcFromString,
  ipAddress: Schema.NullOr(Schema.String),
  userAgent: Schema.NullOr(Schema.String),
  createdAt: Model.DateTimeInsert,
  updatedAt: Model.DateTimeUpdate
}) {}

// -----------------------------------------------------------------------------
// Account
// -----------------------------------------------------------------------------

/**
 * The synthetic issuer used by the email/password identity of a user. The
 * account's `accountId` is the user's id.
 *
 * @category constructors
 * @since 1.0.0
 */
export const CredentialIssuer = "local:credential"

/**
 * Builds the synthetic issuer used for plain OAuth2 providers that publish no
 * OIDC issuer URL (GitHub, for example). OIDC providers use their real issuer.
 *
 * @category constructors
 * @since 1.0.0
 */
export const oauthIssuer = (providerId: string): string => `local:oauth:${providerId}`

/**
 * A sign-in method belonging to a user: either the local email/password
 * credential or a linked OAuth provider account.
 *
 * **Details**
 *
 * `(issuer, accountId)` is the compound unique key and the only identity used
 * to match an incoming OAuth sign-in to an existing account. `accountId` is the
 * provider's stable subject — never an e-mail address. Tokens and the password
 * hash are `Model.Sensitive` and never appear in JSON.
 *
 * @category models
 * @since 1.0.0
 */
export class Account extends Model.Class<Account>("effect-auth/Account")({
  id: Model.UuidV7Insert(AccountId),
  issuer: Schema.String,
  accountId: Schema.String,
  providerId: Schema.String,
  userId: UserId,
  accessToken: Model.Sensitive(Schema.NullOr(Schema.String)),
  refreshToken: Model.Sensitive(Schema.NullOr(Schema.String)),
  idToken: Model.Sensitive(Schema.NullOr(Schema.String)),
  accessTokenExpiresAt: Schema.NullOr(Schema.DateTimeUtcFromString),
  refreshTokenExpiresAt: Schema.NullOr(Schema.DateTimeUtcFromString),
  scope: Schema.NullOr(Schema.String),
  passwordHash: Model.Sensitive(Schema.NullOr(Schema.String)),
  createdAt: Model.DateTimeInsert,
  updatedAt: Model.DateTimeUpdate
}) {}

// -----------------------------------------------------------------------------
// Verification
// -----------------------------------------------------------------------------

/**
 * Builds the `identifier` of an e-mail verification row.
 *
 * @category constructors
 * @since 1.0.0
 */
export const emailVerifyIdentifier = (email: string): string => `email-verify:${normalizeEmail(email)}`

/**
 * Builds the `identifier` of a password reset row.
 *
 * @category constructors
 * @since 1.0.0
 */
export const passwordResetIdentifier = (userId: UserId): string => `password-reset:${userId}`

/**
 * Builds the `identifier` of an OAuth state row.
 *
 * @category constructors
 * @since 1.0.0
 */
export const oauthStateIdentifier = (nonce: string): string => `oauth-state:${nonce}`

/**
 * A single-use, expiring value: an e-mail verification token, a password reset
 * token, or a pending OAuth state.
 *
 * **Details**
 *
 * `identifier` is namespaced by purpose (see {@link emailVerifyIdentifier},
 * {@link passwordResetIdentifier}, {@link oauthStateIdentifier}) and indexed.
 * Only the hash of the secret value is stored, and consumption is a single
 * atomic delete-returning statement, which is what makes reset tokens,
 * verification links and OAuth state genuinely single-use under concurrency.
 *
 * @category models
 * @since 1.0.0
 */
export class Verification extends Model.Class<Verification>("effect-auth/Verification")({
  id: Model.UuidV7Insert(VerificationId),
  identifier: Schema.String,
  valueHash: Model.Sensitive(Schema.String),
  payload: Model.Sensitive(Schema.NullOr(Schema.String)),
  expiresAt: Schema.DateTimeUtcFromString,
  createdAt: Model.DateTimeInsert,
  updatedAt: Model.DateTimeUpdate
}) {}

// -----------------------------------------------------------------------------
// Public (JSON) projections
// -----------------------------------------------------------------------------

/**
 * The client-facing projection of a {@link User}.
 *
 * @category models
 * @since 1.0.0
 */
export const UserPublic = User.json

/**
 * The type of a {@link UserPublic}.
 *
 * @category models
 * @since 1.0.0
 */
export type UserPublic = typeof User.json.Type

/**
 * The client-facing projection of a {@link Session}. It omits `tokenHash`.
 *
 * @category models
 * @since 1.0.0
 */
export const SessionPublic = Session.json

/**
 * The type of a {@link SessionPublic}.
 *
 * @category models
 * @since 1.0.0
 */
export type SessionPublic = typeof Session.json.Type

/**
 * The client-facing projection of an {@link Account}. It omits every token and
 * the password hash.
 *
 * @category models
 * @since 1.0.0
 */
export const AccountPublic = Account.json

/**
 * The type of an {@link AccountPublic}.
 *
 * @category models
 * @since 1.0.0
 */
export type AccountPublic = typeof Account.json.Type

/**
 * The payload returned by every endpoint that establishes or reads a session.
 *
 * @category models
 * @since 1.0.0
 */
export const SessionWithUser = Schema.Struct({
  user: UserPublic,
  session: SessionPublic
})

/**
 * The type of a {@link SessionWithUser}.
 *
 * @category models
 * @since 1.0.0
 */
export type SessionWithUser = typeof SessionWithUser.Type

/**
 * The payload returned by sign-up.
 *
 * **Details**
 *
 * `session` is `null` when the configuration does not hand a session out on
 * registration — `emailPassword.requireEmailVerification` is on (the address is
 * not proven yet) or `autoSignIn` is off. The user was still created, so this
 * is a success, and the field is nullable rather than the endpoint having two
 * success shapes.
 *
 * @category models
 * @since 1.0.0
 */
export const SignUpResponse = Schema.Struct({
  user: UserPublic,
  session: Schema.NullOr(SessionPublic)
})

/**
 * The type of a {@link SignUpResponse}.
 *
 * @category models
 * @since 1.0.0
 */
export type SignUpResponse = typeof SignUpResponse.Type
